name: "web_app"
mode: "dev"
port: 8080
start_time: "2022-05-29"
machine_id: 1
log:
  level: "debug"
  filename: "moon.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "moon"
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  dbname: 0
  pool_size: 100